### PR TITLE
Create home screen and form

### LINKED ISSUE #33: Add Home Screen
# Home Screen
**Given**: a user wants to play the game
**When**: a user navigated to the URL
**Then**: the active event will be shown
**Then**: The user can input fname, lname, and email
**Then**: The user can push play button to start the game

### PR DESCRIPTION
**Pull request by drteresavasquez**
Fixes #33 

# Fetching Instructions
```shell
git fetch --all
git checkout add-home-screen
```

# Description
Created home screen and added form that adds user info to local storage

# List of changes
- Moved file locations for cleaner code
- Create home screen

# Checklist:
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation specific to my parts
- [X] My changes generate no new warnings

# To test
- Navigate to home screen
- complete form
- open application in dev tools
- check local storage for `user` should have the values you entered

Screen Shot 2020-10-29 at 10 48 20 AM

### CODE REVIEW

**Review by SummerPerkey — COMMENTED** [review]
Home page issues:

- Required fields validation is missing

- Favicon needs to be added

- Page Name needs to be added

- No character limitation requirements stated

@drteresavasquez

**Review by ankajgoel — COMMENTED** [review]
Deleted--test comment

**Comment by drteresavasquez** [comment]
@SummerPerkey @ankajgoel set requirements and validations to HTML inputs

**Comment by drteresavasquez** [comment]
Per patrick, the ZIP is now required

**Review by TrinityTerry — APPROVED** [review]

**Comment by SummerPerkey** [comment]
• Required fields validation is missing
		Retested - fields now marked 
		Retest - all fields now required
	• Favicon needs to be added
	• Page Name needs to be added
	       To be completed in future PR
	• No character limitation requirements stated
                 Retest - zip code only accepts max 5 numerals

**Pull request merged**
